sudo: required
language: python

python:
  - "2.7"

install:
  - pip install -r requirements-test.txt

script:
  - nosetests

services:
  - docker

before_install:
  - docker build master/ -t "master"
  - docker build minion/ -t "minion"
  - docker run -d --name "master" master
  - docker run -d --name "minion" minion