sudo: required
language: python

python:
  - "2.7"

install:
  - pip install -r requirements-test.txt

before_script:
  - export BRANCH=$(if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "develop"]; then echo $TRAVIS_BRANCH; else echo "feature_test"; fi)

script:
  - nosetests

services:
  - docker

before_install:
  - docker build master/ -t "master:$BRANCH"
  - docker build minion/ -t "minion:$BRANCH"
  - docker run -d --name "master" master:$BRANCH 
  - docker run -d --name "minion" minion:$BRANCH