sudo: required
language: python

python:
  - "2.7"

install:
  - pip install -r requirements-test.txt

script:
  - nosetests

services:
  - docker

before_install:
  - docker build master/ -t "master:$TRAVIS_BRANCH"
  - docker build minion/ -t "minion:$TRAVIS_BRANCH"
  - docker run -d --name "master" master:$TRAVIS_BRANCH 
  - docker run -d --name "minion" minion:$TRAVIS_BRANCH